# Generated by Django 5.0.7 on 2026-06-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_member_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_members',
            field=models.PositiveIntegerField(blank=True, help_text='Kosongkan jika tanpa batas kuota peserta', null=True),
        ),
    ]
