# Generated by Django 5.0.7 on 2026-06-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_course_max_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link video YouTube untuk materi ini (opsional)', null=True),
        ),
    ]
